### PR TITLE
remove this shitty feature

### PR DESCRIPTION
**Pull request by maxchrr**
dumbest feature ever
no test, no pain, if it still work it's magic ✨

### CODE REVIEW

**Comment by maxchrr** [comment]
just don't forget to remove the content from your cdn

**Comment by MatthieuCoder** [comment]
I'll ask @GabeeTheFinch for review

**Comment by GabeeTheFinch** [comment]
After careful consideration and respectful reviewing.

No.
If the bot doesn't, I fucking will

**Comment by maxchrr** [comment]
> After careful consideration and respectful reviewing.
> 
> No. If the bot doesn't, I fucking will

there are thoughtful mentions and silly mentions

**Comment by GabeeTheFinch** [comment]
Yes but thanks to that incredible feature there are less silly mentions :D

**Comment by MatthieuCoder** [comment]
too radical, will implement a similar more granular system

**Pull request closed without merging**
