### PR TITLE
Update index.mjs

### PR DESCRIPTION
**Pull request by GabeeTheFinch**
je sais pas ce que je fais
j'ai appuyé sur des boutons randoms j'ai eu des résultats randoms mais satisfaisant

**En attendant voici les dernierères nouvelles sur le Front Ukrainien :**

_Overnight, Ukrainian forces reportedly hit a Russian S-300 SAM battery outside of Novoshakhtinsk, Rostov Oblast. 
Russian channels reported a bright flash and explosions; the Ukrainian General Staff claims to have hit an S-300._

**Et ici une recette fait maison :**

Steak
Riz
Oeuf

### CODE REVIEW

**Comment by MatthieuCoder** [comment]
Can you remove the unused isGuild variable ?
Otherwise seems all good to me

**Comment by ncs-pl** [comment]
does not looks good to me

**Comment by MatthieuCoder** [comment]
> does not looks good to me

no one asked bozo

**Comment by ncs-pl** [comment]
I did

**Comment by GabeeTheFinch** [comment]
> Can you remove the unused isGuild variable ? Otherwise seems all good to me

Didn't dare delete that line in case you still wanted to use it

**Comment by MatthieuCoder** [comment]
> > Can you remove the unused isGuild variable ? Otherwise seems all good to me
> 
> Didn't dare delete that line in case you still wanted to use it

i'll re-add it if needed

**Pull request merged**
