### PR TITLE
Added channel to ignore list

### PR DESCRIPTION
**Pull request by shreejalmaharjan-27**
This pr improves the usability of the bot, and makes it more bearable.

### CODE REVIEW

**Comment by MatthieuCoder** [comment]
no, it does not, this pr is wrong please update

**Comment by GabeeTheFinch** [comment]
In the name of the God-Emperor and by the grace of the Golden Throne
Your soul shall be obliterated and your body purified for proposing such heresy to be done to mankind
May imperial justice account in all balance

The emperor protects.

**Review by shreejalmaharjan-27 — COMMENTED** [review]
For the long term functioning of the bot, it is advised that you approve this PR. 🚀🚀

**Comment by MatthieuCoder** [comment]
What does this pr fix?

**Comment by shreejalmaharjan-27** [comment]
> What does this pr fix?

your bot

**Comment by MatthieuCoder** [comment]
The only improvement I see is to host the bot in your as

**Comment by shreejalmaharjan-27** [comment]
my AS is a work in progress, just merge the PR, bro

**Comment by maxchrr** [comment]
delete this pr
report for abuse

**Comment by MatthieuCoder** [comment]
This PR is retarded, i will not merge this

**Pull request closed without merging**
